### ISSUE TITLE
Coping with the rJava installation

### ISSUE THREAD

**Issue by ablaette** [PolMine/bignlp#9]
The bignlp package is inconceivable without using rJava as an interface to Stanford CoreNLP. But rJava is notoriously difficult to install. The [this thread if the R-devel discussion forum](https://r.789695.n4.nabble.com/status-of-Java-amp-rJava-td4762085.html) for a respective discussion. We should try to give effective instructions as possible in the README to ameliorate the pain installing rJava may cause.

**Comment by msaeltzer** [comment]
Dear Team, 

I tried to install bignlp but installation fails with the message "No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures."
and 
Error: Failed to install 'bignlp' from GitHub:
  (converted from warning) installation of package ‘C:/Users/admin/AppData/Local/Temp/Rtmpycr8eu/file5e786edf2462/bignlp_0.0.4.tar.gz’ had non-zero exit status

I reinstalled Java, made sure it is 64bit just as R, set the system environment, made sure in runs in windows console, tested rjava-> executes simple commands, no error.

Also managed to import xlsx with the rjava based xlsx package. 

Any idea where the problem might be?

Best regards, Marius
